question_data = [{"category": "Science & Nature", "type": "boolean", "difficulty": "medium", 
                  "question": "A person can get sunburned on a cloudy day.", 
                  "correct_answer": "True", "incorrect_answers": ["False"]}, 
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Shrimp can swim backwards.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
                  {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "In the periodic table, Potassium&#039;s symbol is the letter K.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Sugar contains fat.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Sound can travel through a vacuum.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "The most frequent subconscious activity repeated by the human body is blinking.", "correct_answer": "False", "incorrect_answers": ["True"]}]
